version: '3.8'

services:
  boringproxy:
    # Build from source using the robust Dockerfile we created.
    build: .
    container_name: boringproxy
    restart: unless-stopped

    # The correct command for the binary your environment produces.
    command:
      - "server"
      - "-behind-proxy"
      - "-https-port"
      - "8100"
      - "-admin-domain"
      - "admin.tunnel.183816.xyz"
      - "-ssh-server-port" 
      - "8443"
      - "-db-dir"
      - "/data"

    ports:
      - '8443:8443'

    volumes:
      - boringproxy_data:/data

    # This connects the service to the network that Traefik is on.
    networks:
      - coolify_net
    
    labels:
      # --- Manual Traefik Labels ---
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.boringproxy.rule=Host(`admin.tunnel.183816.xyz`)"
      - "traefik.http.routers.boringproxy.entrypoints=websecure"
      - "traefik.http.routers.boringproxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.boringproxy.loadbalancer.server.port=8100"
      - "traefik.http.services.boringproxy.loadbalancer.server.scheme=https"

      # --- Coolify Management Labels ---
      - "coolify.managed=true"
      - "coolify.applicationId=3"
      - "coolify.type=application"
      - "coolify.resourceName=boringproxy-git"
      - "coolify.projectName=main"
      - "coolify.serviceName=boringproxy-git"
      - "coolify.environmentName=production"

volumes:
  boringproxy_data:

networks:
  # This section correctly defines 'coolify_net' as an alias for the
  # existing external network named 'coolify'.
  coolify_net:
    name: coolify
    external: true
