version: '3.8'

services:
  boringproxy:
    build: .
    container_name: boringproxy
    restart: unless-stopped

    command:
      - "server"
      - "-behind-proxy"
      # Changed admin UI port to 8100 as requested
      - "-https-port"
      - "8100"
      - "-admin-domain"
      - "admin.tunnel.183816.xyz"
      # Using the legacy flag your build requires
      - "-ssh-server-port"
      - "8443"
      - "-db-dir"
      - "/data"

    ports:
      - '8443:8443'

    volumes:
      - boringproxy_data:/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.boringproxy.rule=Host(`admin.tunnel.183816.xyz`)"
      - "traefik.http.routers.boringproxy.entrypoints=websecure"
      # Fixed resolver name as requested
      - "traefik.http.routers.boringproxy.tls.certresolver=letsencrypt"
      # Pointing Traefik to the new admin port
      - "traefik.http.services.boringproxy.loadbalancer.server.port=8100"
      # Telling Traefik to use HTTPS for the internal connection
      - "traefik.http.services.boringproxy.loadbalancer.server.scheme=https"

volumes:
  boringproxy_data:

networks:
  proxy:
    external: true
