version: '3.8'

services:
  boringproxy:
    build: .
    container_name: boringproxy
    restart: unless-stopped

    command:
      - "server"
      - "-behind-proxy"
      - "-https-port"
      - "8100"
      - "-admin-domain"
      - "admin.tunnel.183816.xyz"
      - "-ssh-server-port"
      - "8443"
      - "-db-dir"
      - "/data"

    ports:
      - '8443:8443'

    volumes:
      - boringproxy_data:/data

    # The 'networks' key has been removed from the service. Docker Compose will
    # automatically connect this container to the new default network it creates.

    labels:
      - "traefik.enable=true"
      # The 'traefik.docker.network' label is removed, as we are no longer
      # referencing the 'proxy' network.
      - "traefik.http.routers.boringproxy.rule=Host(`admin.tunnel.183816.xyz`)"
      - "traefik.http.routers.boringproxy.entrypoints=websecure"
      - "traefik.http.routers.boringproxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.boringproxy.loadbalancer.server.port=8100"
      - "traefik.http.services.boringproxy.loadbalancer.server.scheme=https"

volumes:
  boringproxy_data:

