version: '3.8'

services:
  boringproxy:
    # 1. Build from Source: The only reliable way to get a working image,
    # as we discovered the public images are broken or outdated.
    build: .
    
    # 2. Clean Container Name: A simple, predictable name.
    container_name: boringproxy
    restart: unless-stopped

    # 3. Correct Command: This uses the legacy "-ssh-server-port" flag,
    # which is what your build environment has proven to require, based on your logs.
    command:
      - "server"
      - "-behind-proxy"
      - "-admin-domain"
      - "admin.tunnel.183816.xyz"
      - "-http-port"
      - "8000"
      - "-ssh-server-port"
      - "8443"
      - "-db-dir"
      - "/data"

    # 4. Correct Port Mapping: Exposes only the dedicated tunnel port (8443)
    # to avoid conflicts with Traefik on ports 80/443.
    ports:
      - '8443:8443'

    # 5. Persistent Storage: A named volume to store all user and tunnel data.
    volumes:
      - boringproxy_data:/data

    # 7. Traefik Labels: The essential instructions for your Traefik instance.
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.boringproxy.rule=Host(`admin.tunnel.183816.xyz`)"
      - "traefik.http.routers.boringproxy.entrypoints=websecure"
      - "traefik.http.routers.boringproxy.tls.certresolver=myresolver" # IMPORTANT: Replace with your resolver name
      - "traefik.http.services.boringproxy.loadbalancer.server.port=8000"

# --- Top-Level Definitions ---
# These declare the external resources the service depends on.
volumes:
  boringproxy_data:

