version: '3.8'

services:
  boringproxy:
    build: .
    container_name: boringproxy
    restart: unless-stopped

    # --- THE NEW, SIMPLIFIED COMMAND ---
    command:
      - "server"
      - "-behind-proxy"
      # This flag is now critical. It tells boringproxy to accept plain HTTP.
      - "-allow-http"
      # We now use -http-port to listen for plain HTTP on the internal admin port.
      - "-http-port"
      - "8100"
      - "-admin-domain"
      - "admin.tunnel.183816.xyz"
      # Using the legacy flag your build requires.
      - "-ssh-server-port" 
      - "8443"
      - "-db-dir"
      - "/data"

    ports:
      - '8443:8443'

    volumes:
      - boringproxy_data:/data

    networks:
      - coolify_net
    
    # --- THE NEW, SIMPLIFIED LABELS ---
    # All complex transport and healthcheck labels have been removed.
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # --- Router Configuration ---
      - "traefik.http.routers.boringproxy.rule=Host(`admin.tunnel.183816.xyz`)"
      - "traefik.http.routers.boringproxy.entrypoints=websecure"
      - "traefik.http.routers.boringproxy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.boringproxy.service=boringproxy"

      # --- Service Configuration ---
      # We no longer need 'server.scheme=https' because Traefik's default is HTTP.
      - "traefik.http.services.boringproxy.loadbalancer.server.port=8100"
      
      # --- Coolify Management Labels ---
      - "coolify.managed=true"
      - "coolify.applicationId=3"
      - "coolify.type=application"
      - "coolify.resourceName=boringproxy-git"
      - "coolify.projectName=main"
      - "coolify.serviceName=boringproxy-git"
      - "coolify.environmentName=production"

volumes:
  boringproxy_data:

networks:
  coolify_net:
    name: coolify
    external: true
